version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: task_postgres
    environment:
      POSTGRES_DB: testdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  tasks-app:
    build: .
    container_name: task-container
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=postgres
    depends_on:
      - postgres

volumes:
  postgres-data: